@setfilename MLP.info
@documentencoding UTF-8

@settitle MLP

@copying
Copyright (c) barnards 2023
@end copying

@titlepage
@title MLP
@subtitle Implementation of the MLP project»

@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@headings off

@contents

@ifnottex
@node Top
@top Foo Compiler
@insertcopying
@end ifnottex

@menu
* Description:
* The MLP:
@end menu

@node Description
@chapter Description

@itemize @bullet
@item
Multy layer Perceptrone which have 2 structures graph and Matrix which can recognize English Alphabet letters
@end itemize

@node The MLP
@chapter The MLP

@itemize @bullet
@item
Part 1. Perceptrone
@itemize @minus
@item
Multy layer Perceptrone which have 2 structures graph and Matrix which can recognize English Alphabet letters
@item
Draw or upload letter to your draw place and Perceptrone will start recognize letters 
@item
You can draw by pen
@end itemize
@item
Part 2. Research
@itemize @minus
@item
Research how faster work Perceptrone 
@item
We Compare how good our Perceptrone is working and can understand which Perceptrone structure will faster for our targe
@item
and we will see best result on our graph and result table
@item
@end itemize
@item
@bye


